### ISSUE TITLE
Problem when uploading an animated GIF

### ISSUE THREAD

**Issue by blocknotes** [MaisonetteWorld/magine#67]
Using the CMS and editing the /index page, I tried to set the same image from legacy on the last `category_taxon_shop` block. The image seems to be saved but when I reload the page it is missing. Inspecting the resulting URL the image is unavailable.

Used image: https://d1lfvmh6v1tumg.cloudfront.net/media/cmsimage/639147/original/LeScoop_4Slower.gif?1582563648

**Comment by KempfCreative** [comment]
I have done some research into this, including running a test on the lambda. Here is what I have found:

1. As is, the gif process is throwing errors and not actually sending any image data to S3. I have no narrowed down what is actually causing this error yet.
2. Running the magick convert commands locally on an animated gif won't throw errors, but what it will do is _increase_ the size of the gif. Turns out, setting any kind of `thumbnail` or `resize` commands actually removes the LZW compression, since it isn't compatible with that compression style.
3. Using any imagemagick resize commands will destroy the image ratio. This causing clipping on one dimension. I was able to fix this by deconstructing each frame to its own image, resizing that, and the coalescing that into an animated gif. However, that results in a higher image size than the original unless the resize is greater than 20% of the total size.

A few options exist:
1. Use magick to reduce the color space to reduce overall image size. E.G. taking the linked image (300kb) and running `magick convert ~/Downloads/LeScoop_4Slower.gif +dither -layers Optimize -colors 32 ~/Downloads/magick-1.gif` will result in a file that is identical, but 22% smaller (234kb). 
2. If we then use `gifsicle` to resize ONLY, e.g. `gifsicle --resize-width 300 ~/Downloads/magick-1.gif -o ~/Downloads/gifsicle-resized-1.gif` results in a file that is resized, retaining the ratio, and is 17% smaller. (195kb). 
3. The two processes together are reducing the original image by 35%, and could be variable based on original image size and complexity.
